Improve scaling change message to request further user action.
BuddiesOfBudgie/budgie-desktop pull request #120
Opened 2022-05-09 09:13 UTC by fossfreedom

## Description
Testing of various scaling changes across different monitor and
graphic driver types shows that budgie desktop popovers and other
elements of the GUI do not always refresh correctly.  As a quick
win lets prompt the user to restart their session to allow
the desktop to refresh & resize properly.

![Screenshot from 2022-05-09 10-01-34](https://user-images.githubusercontent.com/996240/167378494-4cf4c664-620e-4890-94f1-9a9ad78db6f3.png)

As an aside there doesn't appear to be any way to force mutter based dialogs to ensure messages span over more than one button.  Odd - just odd.

As discussed on matrix/development with @EbonJaeger - but tried to further reduce the message size to improve appearance without affecting potential translation understanding.

### Submitter Checklist

- [X] Squashed commits with `git rebase -i` (if needed)
- [X] Built budgie-desktop and verified that the patch worked (if needed)

2022-05-09 09:22 UTC, JoshStrobl requested changes
:stop_sign: (GitHub wanted a comment)

2022-05-09 11:02 UTC, fossfreedom commented
![Screenshot from 2022-05-09 11-57-49](https://user-images.githubusercontent.com/996240/167397050-f960db4c-4117-408b-95dc-38e51493a02a.png)

2022-05-13 22:47 UTC, JoshStrobl commented
LGTM. Went ahead and updated the description since it was hard wrapping after 80 columns. PR itself looks good. Thanks!

2022-05-13 22:47 UTC, JoshStrobl approved these changes

2022-05-13 22:47 UTC, merged