Reset ITL buttons if group updated while pinned
BuddiesOfBudgie/budgie-desktop pull request #138
Opened 2022-06-06 01:25 UTC by serebit

## Description

Rather than always removing a button wrapper in ITL when its group is replaced, this patch adds a check for whether or not the button is pinned. If it is, the applet instead removes the button's class group and first_app, then updates it visually, essentially cutting it off from the group change. Then the function proceeds normally, which creates a new button with the new group. For example, if the LibreOffice launcher is pinned and a document is opened within it, the LibreOffice launcher button will cease to show as "running", and a new button will appear for the application associated with that document.

Fixes #107.

### Submitter Checklist

- [x] Squashed commits with `git rebase -i` (if needed)
- [x] Built budgie-desktop and verified that the patch worked (if needed)

2022-06-11 23:49 UTC, JoshStrobl approved these changes
Patch looks good to me but going to pull down locally to test before merge :)

2022-06-11 23:58 UTC, JoshStrobl commented
Unfortunately, my panel crashed with this:

```
** (budgie-panel:415696): CRITICAL **: 02:51:15.744: budgie_abomination_app_group_get_windows: assertion 'self != NULL' failed

** (budgie-panel:415696): CRITICAL **: 02:51:15.744: icon_button_has_window: assertion 'self != NULL' failed

** (budgie-panel:415696): CRITICAL **: 02:51:15.744: icon_button_update: assertion 'self != NULL' failed

** (budgie-panel:415696): CRITICAL **: 02:51:15.745: icon_button_has_window: assertion 'self != NULL' failed

** (budgie-panel:415696): CRITICAL **: 02:51:15.745: icon_button_update: assertion 'self != NULL' failed

** (budgie-panel:415696): CRITICAL **: 02:51:20.435: icon_button_has_window: assertion 'self != NULL' failed

** (budgie-panel:415696): CRITICAL **: 02:51:20.435: icon_button_update: assertion 'self != NULL' failed
```

Steps I performed:

- Launched LO Writer. Worked fine. Pinned, closed app. Button remained as expected.
- Launded LO Impress, it created a button for Impress as I expected, as well as one for a secondary dialog it provided prompting me to choose a template. I closed the dialog, which removed that button. I proceeded to close Impress.
- I then relaunched the Writer and got the crash.

I tested further and found that if I launch Writer without it pinned, pin it while it is open, close the app, then proceed to launch it, the panel will reliably segfault.

Unfortunately, I tested it with other apps like GNOME Boxes and am getting the same issue. So this PR cannot land.

2022-06-11 23:59 UTC, JoshStrobl requested changes
Marking as request changes.

2022-06-12 00:03 UTC, JoshStrobl commented
Alright, I bisected the change further @serebit and the good news is, it isn't this commit.

The bad news is it is 991bd56f54ea0951292592844e6f89ec687f9d65

2022-06-12 05:36 UTC, serebit commented
Pain.

2022-06-12 18:31 UTC, serebit commented
@JoshStrobl Fixed in master, as far as I can tell. Pinning, closing, and then launching GNOME Boxes and LibreOffice Writer no longer segfaults the panel on my machine.

2022-07-09 15:40 UTC, JoshStrobl commented
Can confirm no explosions, works as intended :)

2022-07-09 15:40 UTC, merged