Don't use the notification settings for DND
BuddiesOfBudgie/budgie-desktop pull request #41
Opened 2022-01-18 21:28 UTC by EbonJaeger

## Description
This removes our dependence on GNOME settings schemas for Do Not Disturb functionality (again). I decided to make this a PR to get other eyes on it in case there's something I missed.

### Submitter Checklist

- [x] Squashed commits with `git rebase -i` (if needed)
- [x] Built budgie-desktop and verified that the patch worked (if needed)

2022-01-18 21:36 UTC, EbonJaeger commented
Also cc: @fossfreedom, since more control center stuff might be able to be hidden after this.

2022-01-18 21:55 UTC, fossfreedom commented
> Also cc: @fossfreedom, since more control center stuff might be able to be hidden after this.

Currently in git master B-C-C the 'do not disturb option' is not visible

2022-01-20 16:37 UTC, JoshStrobl requested changes
Otherwise LGTM, thanks!

2022-01-20 17:33 UTC, JoshStrobl commented
LGTM, thanks!

2022-01-20 17:33 UTC, merged