Simplify Raven notification group
BuddiesOfBudgie/budgie-desktop pull request #452
Opened 2023-09-09 19:00 UTC by EbonJaeger

## Description
This does a couple of things. First, when constructing a notification group, just get the image directly from our Notification object. We did all the work to get the correct image, let's actually use it.

Secondly, remove our HashTable mapping application name to notification group. We don't need it; anything it was used for we can get from the ListBox. This avoids having to keep track of groups in multiple data structures (the table and the list box). This makes the code easier to maintain, and slightly more memory efficient.

The NotificationGroup widget has been changed to a `Gtk.ListBoxRow` to make it easier to find and remove groups from the view.

Lastly, switch to `ngettext` to build the text for the notification view header instead of an if/elseif chain.

Fixes #450 

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)
- [x] Built budgie-desktop and verified that the patch worked (if needed)

2023-09-17 09:10 UTC, JoshStrobl commented
Testing with Discord and seems a bit busted. Incorrect title and notification group icons aren't that of the application, just of the first icon of the first notification you get.

![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/156574/d7eca452-5aed-49a5-955f-9d5ac99e77bd)

2023-09-27 21:43 UTC, serebit requested changes
Built-in theme needs a style update to coincide with this, the new notification items look off with the existing styling.

2023-09-28 09:59 UTC, JoshStrobl commented
@serebit Could you clarify what styling changes you are referring to?

- Notification Widget has not seen any changes with this PR. The notification widget clones attributes from the Notification itself.
- Notification Group, which has seen changes, is already referenced in our internal styling by its class name `raven-notifications-group`. The Raven Notifications Group Header is still aligned with group item headers, which was the purpose of margin and padding offsets, and the use of the inner box instead of the group itself being the box is still valid as we referenced the group without a parent selector (so it can be any child) and the inner list is still a valid selector
- Notification View is referenced by `raven-notifications-view` , saw no related changes from what I can tell.

It looks identical to me.

2023-09-30 15:41 UTC, JoshStrobl approved these changes
LGTM!

2023-09-30 15:43 UTC, serebit approved these changes

2023-09-30 15:43 UTC, merged