New windowing tracker and large refactor of IconTasklist
BuddiesOfBudgie/budgie-desktop pull request #553
Opened 2024-04-02 20:33 UTC by EbonJaeger

## Description

This all started off as a replacement of Abonination with a new module leveraging `libxfce4windowing`. Because of the tight coupling between IconTasklist and Abonination, it quickly became way more than that, becomming a large-scale rewrite of IconTasklist.

A new module, named "Windowing," has been written as a way to wrap and extend `libxfce4windowing`, making code that uses it easier to maintain, as well as making more code reusable. It is a combination, in essense, of AppSys and Abomination.

The functionality of IconTasklist should be the same as the old version. If anything, there might be an additional feature or two. Previously, theme designers had no way to change the look of an IconButton if a window requested urgency. Now, a new CSS class (`needs-attention`) is applied when a window becomes urgent, and is removed when urgency is no longer needed.

Popovers for right-clicking an IconButton have seen a slight redesign. Pages for window controls are now created and destroyed on-demand, which should yield a small improvement to memory usage.

Some X11-specific code still exists; it's currently unavoidable while we're still an X11-only desktop environment. However, this puts us in a much better place to be able to support both X11 and Wayland in IconTasklist, and any other code that will use the new Windowing module.

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)
- [x] Built budgie-desktop and verified that the patch worked (if needed)

2024-04-06 16:39 UTC, JoshStrobl requested changes

2024-04-06 16:39 UTC, JoshStrobl commented on src/panel/applets/icon-tasklist/Widgets/IconButton.vala
> +		}
```suggestion
		if (window_group == null) return Gdk.EVENT_STOP;
```

2024-04-06 16:39 UTC, JoshStrobl commented on src/panel/applets/icon-tasklist/Widgets/IconButton.vala
> +		}
```suggestion
		if (windows.is_empty()) return base.draw(ctx);
```

2024-04-06 16:39 UTC, JoshStrobl commented on src/panel/applets/icon-tasklist/Widgets/IconButton.vala
> +		}
```suggestion
		if (!get_active()) return draw_inactive(ctx);
```

2024-04-06 16:39 UTC, JoshStrobl commented on src/panel/applets/icon-tasklist/Widgets/IconButton.vala
> +			icon.animate_attention(panel_position);
What about the internal theme?

2024-04-06 16:39 UTC, JoshStrobl commented on src/panel/applets/icon-tasklist/Widgets/IconButton.vala
> +			set_tooltip_text(app?.name ?? active_window?.get_name() ?? "");
```suggestion
			if (!pinned) return;
			window_group = null;

			var active_window = window_group?.get_active_window() ?? window_group?.get_last_active_window();
			set_tooltip_text(app?.name ?? active_window?.get_name() ?? "");
```

2024-04-06 16:39 UTC, JoshStrobl commented on src/panel/applets/icon-tasklist/Widgets/IconButton.vala
> +		}
```suggestion
		// prevents apps making the panel massive when the icon initially gets added
		icon.pixel_size = (target_icon_size > 0) ? target_icon_size : DEFAULT_ICON_SIZE;
```

2024-04-06 16:39 UTC, JoshStrobl commented on src/windowing/window_mapper.vala
> +				}
```suggestion
				if (desktop_id in applications) return applications[desktop_id];
```

2024-04-06 16:39 UTC, JoshStrobl commented on src/windowing/window_mapper.vala
> +				}
```suggestion
				if (info != null) return info;
```

2024-04-06 16:39 UTC, JoshStrobl commented on src/windowing/window_mapper.vala
> +				}
```suggestion
				if (info != null) return info;
```

2024-04-06 17:15 UTC, JoshStrobl commented on src/panel/applets/icon-tasklist/Widgets/ButtonPopover.vala
> +			}
This code can go in, after convo with Evan I'm gonna implement a custom heart icon and one with a green accent / fill for use when it's favorited.

The goal of this change was to have it stand out when favorited and not use the star, and under Fluent it looks good but Papirus it looks like hot garbage. So easiest is doing it ourselves.

2024-04-06 21:33 UTC, JoshStrobl approved these changes

2024-04-06 22:11 UTC, serebit requested changes
Code mostly looks good, but I do have some items for clarification and one that I think we should change.

2024-04-06 22:11 UTC, serebit commented on data/icons/status/budgie-app-unfavorited.svg
Could these be themeable? I'm iffy on making these static green and dark grey - depending on the GTK theme, the unfavorited state could be really hard to see. Arc-Dark has this problem (yes I know it's unsupported), and I'm sure others do as well. Maybe a heart outline for unfavorited and a filled in heart with a themeable color for favorited? Similar idea to the way we handle the notifications applet.

2024-04-06 22:11 UTC, serebit commented on src/theme/common/_colors.scss
Por que?

2024-04-06 22:11 UTC, serebit commented on src/windowing/window_mapper.vala
> +			int a_f; // TODO: wat?
wat?

2024-04-06 22:12 UTC, JoshStrobl commented on src/theme/common/_colors.scss
Others were hex, makes it easier to copy into places like Inkscape.

2024-04-15 14:01 UTC, serebit approved these changes

2024-04-15 14:02 UTC, serebit commented on data/icons/status/budgie-app-unfavorited.svg
Resolving conversation—this will be fixed separately.

2024-04-16 14:43 UTC, merged